# Generated by Django 4.0.3 on 2024-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='code',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.AddField(
            model_name='students',
            name='sinf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
